import { describe, expect, it } from 'vitest';
import type { ClassifiedEntry } from '../../kinds';
import { emitTree } from '../index';
import { fixtureInput } from '../test-fixture';
import type { EmitInput } from '../types';

describe('emitTree — AGENTS.md tier (codex / copilot / factory)', () => {
  it('emits only root/nested AGENTS.md and warns once per emittable kind present, labeled by target', () => {
    const result = emitTree(fixtureInput(['codex']));

    expect(result.errors).toEqual([]);
    expect(result.copies).toEqual([]);
    expect(result.files).toEqual([
      {
        path: 'AGENTS.md',
        content:
          '<!-- generated by OuterLayer from .outerlayer/AGENTS.md — edit the source, not this file -->\n' + 'Root instructions.\n',
      },
      {
        path: 'apps/api/AGENTS.md',
        content:
          '<!-- generated by OuterLayer from apps/api/.outerlayer/AGENTS.md — edit the source, not this file -->\n' +
          'API scope instructions.\n',
      },
    ]);
    expect(result.warnings).toEqual([
      { path: 'codex:command', code: 'unsupported_on_target', message: '"command" content is not emitted for codex (AGENTS.md-only tier in v1)' },
      { path: 'codex:mcp', code: 'unsupported_on_target', message: '"mcp" content is not emitted for codex (AGENTS.md-only tier in v1)' },
      { path: 'codex:skill', code: 'unsupported_on_target', message: '"skill" content is not emitted for codex (AGENTS.md-only tier in v1)' },
    ]);
  });

  it('labels the warning with the specific target for copilot and factory too', () => {
    const copilotResult = emitTree(fixtureInput(['copilot']));
    const factoryResult = emitTree(fixtureInput(['factory']));

    expect(copilotResult.warnings.map((w) => w.path)).toEqual(['copilot:command', 'copilot:mcp', 'copilot:skill']);
    expect(factoryResult.warnings.map((w) => w.path)).toEqual(['factory:command', 'factory:mcp', 'factory:skill']);
  });

  it('does not warn for reference or subagent kinds — neither is emitted anywhere in v1, so it is not a target-specific gap', () => {
    const entries: ClassifiedEntry[] = [
      { path: '.outerlayer/notes.md', kind: 'reference', scopePath: '' },
      { path: '.outerlayer/agents/reviewer.md', kind: 'subagent', scopePath: '' },
    ];
    const input: EmitInput = {
      entries,
      contents: new Map(),
      assetPaths: [],
      targets: ['codex'],
    };

    const result = emitTree(input);

    expect(result.files).toEqual([]);
    expect(result.warnings).toEqual([]);
    expect(result.errors).toEqual([]);
  });
});
