import { describe, expect, it } from 'vitest';
import { classifyTree } from '../../classify';
import { emitTree } from '../index';
import { fixtureInput } from '../test-fixture';

describe('emitTree — cursor target (full tier)', () => {
  it('compiles instructions to root/nested AGENTS.md, skills to .agents/skills/, commands (body only), and mcp with ${env:VAR} rewrite', () => {
    const result = emitTree(fixtureInput(['cursor']));

    expect(result.errors).toEqual([]);
    expect(result.copies).toEqual([
      { toPath: '.agents/skills/deploy-checklist/scripts/run.sh', fromSourcePath: '.outerlayer/skills/deploy-checklist/scripts/run.sh' },
      { toPath: '.agents/skills/onboarding/assets/logo.png', fromSourcePath: '.outerlayer/skills/onboarding/assets/logo.png' },
    ]);
    expect(result.warnings).toEqual([
      {
        path: 'mcpServers.api.url',
        code: 'env_ref_no_default',
        message:
          '"${API_URL:-https://api.example.com}" has no Cursor default-value equivalent — emitted as "${env:API_URL}", default dropped',
      },
    ]);
    expect(result.files).toEqual([
      {
        // Frontmatter stays at byte 0 (skill loaders only parse it on line 1);
        // the generated header lands after the closing ---.
        path: '.agents/skills/deploy-checklist/SKILL.md',
        content:
          '---\nname: deploy-checklist\ndescription: Steps to deploy safely.\n---\n' +
          '<!-- generated by OuterLayer from .outerlayer/skills/deploy-checklist/SKILL.md — edit the source, not this file -->\n' +
          'Run the checklist.\n',
      },
      {
        path: '.agents/skills/onboarding/references/setup.md',
        content:
          '<!-- generated by OuterLayer from .outerlayer/skills/onboarding/references/setup.md — edit the source, not this file -->\n' +
          'Install dependencies.\n',
      },
      {
        path: '.agents/skills/onboarding/SKILL.md',
        content:
          '---\nname: onboarding\ndescription: Onboard a new engineer.\n---\n' +
          '<!-- generated by OuterLayer from .outerlayer/skills/onboarding/SKILL.md — edit the source, not this file -->\n' +
          'Read the docs.\n',
      },
      {
        // Body only: description moves to a leading comment, argument-hint has no Cursor equivalent and is dropped silently.
        path: '.cursor/commands/ship.md',
        content:
          '<!-- generated by OuterLayer from .outerlayer/commands/ship.md — edit the source, not this file -->\n' +
          '<!-- Ship the current branch. -->\n' +
          'Run the ship script.\n',
      },
      {
        // No header on mcp.json (JSON takes no comments); ${VAR}/${VAR:-default} rewritten to Cursor's ${env:VAR}.
        path: '.cursor/mcp.json',
        content:
          '{\n  "mcpServers": {\n    "api": {\n      "url": "${env:API_URL}",\n      "headers": {\n        "Authorization": "${env:API_TOKEN}"\n      },\n      "type": "http",\n      "oauth": true\n    }\n  }\n}\n',
      },
      {
        path: 'AGENTS.md',
        content:
          '<!-- generated by OuterLayer from .outerlayer/AGENTS.md — edit the source, not this file -->\n' + 'Root instructions.\n',
      },
      {
        path: 'apps/api/AGENTS.md',
        content:
          '<!-- generated by OuterLayer from apps/api/.outerlayer/AGENTS.md — edit the source, not this file -->\n' +
          'API scope instructions.\n',
      },
    ]);
  });

  it('preserves a command namespace subpath under .cursor/commands/ while a flat command stays at the root of it', () => {
    const paths = ['.outerlayer/commands/ship.md', '.outerlayer/commands/deploy/ship.md'];
    const contents = new Map([
      ['.outerlayer/commands/ship.md', '---\ndescription: Flat.\n---\nFlat body.\n'],
      ['.outerlayer/commands/deploy/ship.md', '---\ndescription: Nested.\n---\nNested body.\n'],
    ]);
    const result = emitTree({ entries: classifyTree(paths).entries, contents, assetPaths: [], targets: ['cursor'] });

    expect(result.errors).toEqual([]);
    expect(result.files.map((f) => f.path).sort()).toEqual([
      '.cursor/commands/deploy/ship.md',
      '.cursor/commands/ship.md',
    ]);
  });

  it('records invalid_mcp_json as a warning and skips the file, rather than throwing, on malformed mcp.json', () => {
    const input = fixtureInput(['cursor']);
    const contents = new Map(input.contents);
    contents.set('.outerlayer/mcp.json', '{ not valid json');

    const result = emitTree({ ...input, contents });

    expect(result.warnings).toEqual([
      { path: '.outerlayer/mcp.json', code: 'invalid_mcp_json', message: expect.any(String) },
    ]);
    expect(result.files.some((f) => f.path === '.cursor/mcp.json')).toBe(false);
  });
});
