/**
 * Spec drift smoke test.
 *
 * There are two OpenAPI specs in this repo:
 *
 *   1. **Runtime spec** (`/v1/openapi.json`) — auto-generated by chanfana
 *      from the Zod schemas on every `BaseRoute` subclass. This is what
 *      SDKs and programmatic consumers fetch; it is the truth about what
 *      the server actually accepts and returns.
 *
 *   2. **Committed spec** (`docs/openapi.yaml`) — the checked-in public
 *      spec, with richer prose and examples than chanfana emits, at the
 *      cost of needing to be kept in sync.
 *
 * This test catches the most common drift: **an operation exists in one
 * spec but not the other**. It compares the set of `(METHOD, path)` pairs
 * — operation-level, not schema-level. Schema-level diffing would fight
 * the curation that makes the hand spec valuable.
 *
 * When this fails it usually means one of:
 *   - You added a route handler but forgot `docs/openapi.yaml`
 *   - You removed a route but forgot to delete its `docs/openapi.yaml` entry
 *   - You added an operation that is intentionally runtime-only or
 *     docs-only — add it to the appropriate exception set below
 */

import { describe, it, expect, beforeAll, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';

// Same mocks as envelope-coverage.test.ts — openApiApp transitively imports
// Supabase, ClickHouse, and the analytics factory.
vi.mock('../analytics-factory', () => ({
  getGatewayAnalyticsService: vi.fn(() => null),
}));
vi.mock('@clickhouse/client-web', () => ({
  createClient: vi.fn(() => ({ query: vi.fn(), insert: vi.fn() })),
}));

import { openApiApp } from '../index';

// ---------------------------------------------------------------------------
// Exceptions — documented asymmetric entries.
//
// Every entry MUST carry a short comment explaining why the asymmetry
// exists and (ideally) when it will be resolved. Stale entries are caught
// by the trailing "exceptions reference live operations" test.
// ---------------------------------------------------------------------------

/**
 * Operations that exist at runtime but NOT in `docs/openapi.yaml`.
 *
 * Adding an entry here means you are consciously keeping a runtime
 * endpoint out of the hand-maintained reference docs. The common case
 * is an infrastructure endpoint (e.g. spec-serving) that would be
 * circular to document inside the spec itself. For a real API endpoint,
 * add it to docs/openapi.yaml instead — external callers only learn
 * about endpoints that are documented.
 */
const RUNTIME_ONLY_OPERATIONS: ReadonlySet<OperationKey> = new Set<OperationKey>([
  // Intentionally empty. Every real /v1/* endpoint should also appear in
  // docs/openapi.yaml. Add an entry only for endpoints whose contract is
  // genuinely outside request/response JSON (e.g. a WebSocket upgrade).
  //
  // `POST /v1/mcp` is NOT an entry here, and never will be: it is mounted
  // directly on the underlying Hono app (`app.post`), bypassing chanfana's
  // route registration (`openApiApp.post`/`registerAuthenticatedRoute`)
  // entirely — one JSON-RPC endpoint dispatching to five tools has no
  // single request/response JSON shape to document as an OpenAPI operation.
  // It is served (auth runs identically to every other /v1/* route) but
  // stays out of BOTH specs by construction — see the regression test below.
]);

/**
 * Operations that exist in `docs/openapi.yaml` but NOT at runtime.
 *
 * Adding an entry here means you are documenting an endpoint that is
 * implemented outside the chanfana `BaseRoute` surface — the only
 * current candidate is a WebSocket upgrade handler whose contract is a
 * frame protocol rather than request/response JSON. For anything else,
 * docs/openapi.yaml is lying to callers and should be updated instead.
 */
const DOCS_ONLY_OPERATIONS: ReadonlySet<OperationKey> = new Set<OperationKey>([]);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type OperationKey = `${string} ${string}`;

const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']);

function extractOperations(paths: Record<string, unknown> | undefined): Set<OperationKey> {
  const out = new Set<OperationKey>();
  if (!paths) return out;
  for (const [path, pathItem] of Object.entries(paths)) {
    if (typeof pathItem !== 'object' || pathItem === null) continue;
    for (const method of Object.keys(pathItem)) {
      if (!HTTP_METHODS.has(method.toLowerCase())) continue;
      out.add(`${method.toUpperCase()} ${path}` as OperationKey);
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('OpenAPI spec drift (runtime ⇄ docs/openapi.yaml)', () => {
  let runtimeOps: Set<OperationKey>;
  let docsOps: Set<OperationKey>;

  beforeAll(async () => {
    const res = await openApiApp.fetch(new Request('http://test.local/v1/openapi.json'));
    const runtimeSpec = (await res.json()) as { paths?: Record<string, unknown> };
    runtimeOps = extractOperations(runtimeSpec.paths);

    const yamlPath = resolve(__dirname, '../../../../../docs/openapi.yaml');
    const yamlText = readFileSync(yamlPath, 'utf8');
    const docsSpec = parseYaml(yamlText) as { paths?: Record<string, unknown> };
    docsOps = extractOperations(docsSpec.paths);
  });

  it('discovers a non-empty set of operations in each spec (sanity)', () => {
    expect(runtimeOps.size).toBeGreaterThan(0);
    expect(docsOps.size).toBeGreaterThan(0);
  });

  it('every runtime operation is either documented or in RUNTIME_ONLY_OPERATIONS', () => {
    const undocumented = [...runtimeOps].filter(
      (key) => !docsOps.has(key) && !RUNTIME_ONLY_OPERATIONS.has(key),
    );
    expect(
      undocumented,
      `operations exist at runtime but not in docs/openapi.yaml:\n  ${undocumented.join('\n  ')}\n\n` +
        `Fix by adding the endpoint to docs/openapi.yaml, or — if intentional — adding ` +
        `it to RUNTIME_ONLY_OPERATIONS with a comment explaining why.`,
    ).toEqual([]);
  });

  it('every docs operation is either served at runtime or in DOCS_ONLY_OPERATIONS', () => {
    const phantom = [...docsOps].filter(
      (key) => !runtimeOps.has(key) && !DOCS_ONLY_OPERATIONS.has(key),
    );
    expect(
      phantom,
      `operations in docs/openapi.yaml do not exist at runtime:\n  ${phantom.join('\n  ')}\n\n` +
        `Fix by removing the stale entry from docs/openapi.yaml, or — if the endpoint ` +
        `is implemented outside chanfana (e.g. WebSocket) — adding it to DOCS_ONLY_OPERATIONS ` +
        `with a comment explaining why.`,
    ).toEqual([]);
  });

  it('the MCP mount never appears in either spec (documented exception, see RUNTIME_ONLY_OPERATIONS)', () => {
    for (const method of ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const) {
      const key: OperationKey = `${method} /v1/mcp`;
      expect(runtimeOps.has(key)).toBe(false);
      expect(docsOps.has(key)).toBe(false);
    }
  });

  it('every exception references a live operation (no stale entries)', () => {
    const staleRuntime: string[] = [...RUNTIME_ONLY_OPERATIONS].filter(
      (key) => !runtimeOps.has(key),
    );
    const staleDocs: string[] = [...DOCS_ONLY_OPERATIONS].filter((key) => !docsOps.has(key));
    expect(
      { staleRuntime, staleDocs },
      `exceptions referencing operations that no longer exist in their respective spec`,
    ).toEqual({ staleRuntime: [], staleDocs: [] });
  });
});
