/**
 * Presentation shape for one user turn's text.
 *
 * A "user" turn in an agent transcript is not only what the developer typed.
 * The harness injects its own XML into the same channel — a slash command is
 * recorded as `<command-name>/clear</command-name>` plus sibling tags, its
 * output as `<local-command-stdout>`, and a constant `<local-command-caveat>`
 * paragraph rides along telling the model to ignore the command. Rendering
 * that channel verbatim shows raw tags where the reader expects a person's
 * words, and gives a wall of identical boilerplate its own turn on screen.
 *
 * The tag vocabulary here must stay in step with the topics pipeline's
 * harness-noise stripper, which classifies the same markers for a different
 * purpose (deciding whether a turn is developer-authored at all).
 */

/** One `<tag>…</tag>` block's inner text, or "" when the tag is absent. */
function tagText(raw: string, tag: string): string {
  const match = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`).exec(raw);
  return match?.[1]?.trim() ?? "";
}

/** Remove every `<tag>…</tag>` block, plus a self-closing/empty variant. */
function stripTag(raw: string, tag: string): string {
  return raw.replace(new RegExp(`<${tag}>[\\s\\S]*?</${tag}>`, "g"), "");
}

/** Tags whose content the reader never needs: pure harness boilerplate. */
const DROPPED_TAGS = ["local-command-caveat"];

/** Tags rendered as structured chrome rather than as body text. */
const LIFTED_TAGS = ["command-name", "command-message", "command-args", "local-command-stdout"];

interface UserTurnView {
  /** The slash command this turn invoked, e.g. "/clear". "" when none. */
  command: string;
  /** Arguments typed after the command. "" when none. */
  commandArgs: string;
  /** Output the command printed back into the transcript. "" when none. */
  stdout: string;
  /** What the developer actually typed, with harness markup removed. */
  text: string;
  /** True when the turn was entirely harness boilerplate — render nothing. */
  empty: boolean;
}

/**
 * Split a raw user-turn string into the developer's words and the harness
 * markup wrapped around them.
 *
 * `command-message` is deliberately not surfaced: it is the command's own
 * description ("clear"), which restates the name and adds nothing next to it.
 */
export function parseUserTurn(raw: string | null | undefined): UserTurnView {
  const source = raw ?? "";
  const command = tagText(source, "command-name");
  const commandArgs = tagText(source, "command-args");
  const stdout = tagText(source, "local-command-stdout");

  let text = source;
  for (const tag of [...DROPPED_TAGS, ...LIFTED_TAGS]) text = stripTag(text, tag);
  text = text.trim();

  // The caveat paragraph is sometimes emitted bare rather than wrapped in its
  // tag. It is a fixed sentence, so match its opening rather than guessing at
  // a length threshold — a developer message never starts this way.
  if (/^Caveat: The messages below were generated by the user while running local commands/.test(text)) {
    text = "";
  }

  return {
    command,
    commandArgs,
    stdout,
    text,
    empty: !command && !commandArgs && !stdout && !text,
  };
}
