#!/usr/bin/env bash
# Bring up a hobby-grade OuterLayer self-host stack.
#
#   ./docker/selfhost-up.sh
#
# Starts Supabase (CLI, on the host), writes docker/.env.selfhost from the
# values it reports, brings up ClickHouse + MinIO + the gateway in Docker,
# migrates ClickHouse, and prints the command that starts the dashboard.
#
# Re-running is safe: generated secrets are written once and preserved; the
# Supabase-derived values are refreshed every run so they cannot drift from the
# instance actually serving.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DASHBOARD="$REPO_ROOT/apps/tenant-dashboard"
ENV_FILE="$REPO_ROOT/docker/.env.selfhost"
COMPOSE=(docker compose -f "$REPO_ROOT/docker/compose.yml" --env-file "$ENV_FILE")

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }
die() { printf '\033[31merror: %s\033[0m\n' "$1" >&2; exit 1; }

# `openssl rand -base64 32` emits '/' and '+', which are fine in a value but
# make the secret annoying to paste into a URL or a shell one-liner. Strip to
# the URL-safe alphabet and keep 32+ characters.
gen_secret() { openssl rand -base64 48 | tr -d '=+/' | cut -c1-40; }

# ---------------------------------------------------------------------------
step "Checking prerequisites"
# ---------------------------------------------------------------------------
command -v docker >/dev/null || die "docker not found — install Docker Desktop or Docker Engine"
docker info >/dev/null 2>&1 || die "the Docker daemon is not responding — start Docker and re-run"
command -v node >/dev/null || die "node not found — Node 22+ is required"
node -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 22 ? 0 : 1)' \
  || die "Node 22+ is required (found $(node --version))"
command -v openssl >/dev/null || die "openssl not found"
command -v curl >/dev/null || die "curl not found"
echo "ok"

# ---------------------------------------------------------------------------
step "Starting Supabase (Postgres + Auth) on the host"
# ---------------------------------------------------------------------------
# `supabase start` is idempotent: it reports the existing instance if one is
# already running rather than failing.
(cd "$DASHBOARD" && npx supabase start >/dev/null) || die "supabase start failed"

SUPABASE_STATUS="$(cd "$DASHBOARD" && npx supabase status -o json 2>/dev/null)"
# The CLI prefixes the JSON with human-readable warnings on some versions.
SUPABASE_STATUS="${SUPABASE_STATUS#*\{}"
SUPABASE_STATUS="{${SUPABASE_STATUS}"

read_status() {
  node -e 'const j=JSON.parse(process.argv[1]);process.stdout.write(j[process.argv[2]]??"")' \
    "$SUPABASE_STATUS" "$1"
}

SUPABASE_API_URL="$(read_status API_URL)"
SUPABASE_DB_URL="$(read_status DB_URL)"
SUPABASE_SECRET_KEY="$(read_status SECRET_KEY)"
SUPABASE_PUBLISHABLE_KEY="$(read_status PUBLISHABLE_KEY)"
SUPABASE_JWT_SECRET="$(read_status JWT_SECRET)"
[ -n "$SUPABASE_API_URL" ] || die "could not read API_URL from 'supabase status -o json'"

# Inside the gateway container, loopback is the container. Same port, host name.
SUPABASE_API_URL_FROM_CONTAINER="${SUPABASE_API_URL/127.0.0.1/host.docker.internal}"
SUPABASE_API_URL_FROM_CONTAINER="${SUPABASE_API_URL_FROM_CONTAINER/localhost/host.docker.internal}"
echo "supabase api: $SUPABASE_API_URL"

# ---------------------------------------------------------------------------
step "Applying database migrations"
# ---------------------------------------------------------------------------
(cd "$DASHBOARD" && npx supabase migration up) || die "supabase migration up failed"

# ---------------------------------------------------------------------------
step "Writing $ENV_FILE"
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  echo "creating with freshly generated secrets"
  CLICKHOUSE_PASSWORD="$(gen_secret)"
  CLICKHOUSE_READ_PASSWORD="$(gen_secret)"
  BLOB_S3_SECRET_ACCESS_KEY="$(gen_secret)"
  SELF_HOST_GATEWAY_SECRET="$(gen_secret)"
  API_KEY_PEPPER="$(gen_secret)"
  TOKEN_ENCRYPTION_KEY="$(gen_secret)"
  OAUTH_STATE_SECRET="$(gen_secret)"
  # Owner-only from the first byte: the file holds live secrets.
  (umask 077; : > "$ENV_FILE")
  cat > "$ENV_FILE" <<EOF
# Generated by docker/selfhost-up.sh. Secrets below are unique to this install.
# The SUPABASE_* block is rewritten on every run; everything else is preserved.

SUPABASE_API_BASE_URL=$SUPABASE_API_URL_FROM_CONTAINER
SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY
SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY
SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET
SUPABASE_DB_URL=$SUPABASE_DB_URL
SUPABASE_API_URL_FROM_HOST=$SUPABASE_API_URL

CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD
CLICKHOUSE_PORT=8123
CLICKHOUSE_READ_USER=analytics_reader
CLICKHOUSE_READ_PASSWORD=$CLICKHOUSE_READ_PASSWORD

BLOB_S3_ACCESS_KEY_ID=minioadmin
BLOB_S3_SECRET_ACCESS_KEY=$BLOB_S3_SECRET_ACCESS_KEY
BLOB_S3_BUCKET=trace-blobs
MINIO_API_PORT=9300
MINIO_CONSOLE_PORT=9301

GATEWAY_PORT=9001
SELF_HOST_GATEWAY_SECRET=$SELF_HOST_GATEWAY_SECRET
SELF_HOST_TRUST_PERIMETER=
API_KEY_PEPPER=$API_KEY_PEPPER

TOKEN_ENCRYPTION_KEY=$TOKEN_ENCRYPTION_KEY
OAUTH_STATE_SECRET=$OAUTH_STATE_SECRET
NEXT_PUBLIC_PLATFORM_ADMIN_EMAIL_DOMAIN=@example.com
FROM_EMAIL=outerlayer@example.com
DASHBOARD_PORT=3002
EOF
else
  echo "exists — refreshing the SUPABASE_* values only"
  # Rewrite in place so a hand-edited port or admin domain survives.
  node - "$ENV_FILE" \
    "$SUPABASE_API_URL_FROM_CONTAINER" "$SUPABASE_SECRET_KEY" \
    "$SUPABASE_PUBLISHABLE_KEY" "$SUPABASE_JWT_SECRET" "$SUPABASE_DB_URL" \
    "$SUPABASE_API_URL" <<'NODE'
const fs = require('node:fs');
const [file, base, secret, publishable, jwt, dbUrl, apiFromHost] = process.argv.slice(2);
const updates = {
  SUPABASE_API_BASE_URL: base,
  SUPABASE_SECRET_KEY: secret,
  SUPABASE_PUBLISHABLE_KEY: publishable,
  SUPABASE_JWT_SECRET: jwt,
  SUPABASE_DB_URL: dbUrl,
  SUPABASE_API_URL_FROM_HOST: apiFromHost,
};
const lines = fs.readFileSync(file, 'utf8').split('\n');
const seen = new Set();
const rewritten = lines.map((line) => {
  const key = line.match(/^([A-Z0-9_]+)=/)?.[1];
  if (!key || !(key in updates)) return line;
  seen.add(key);
  return `${key}=${updates[key]}`;
});
for (const [key, value] of Object.entries(updates)) {
  if (!seen.has(key)) rewritten.push(`${key}=${value}`);
}
fs.writeFileSync(file, rewritten.join('\n'));
NODE
fi
# Covers files created before the umask guard existed, and hand-made copies.
chmod 600 "$ENV_FILE"

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

# ---------------------------------------------------------------------------
step "Building and starting ClickHouse, MinIO, and the gateway"
# ---------------------------------------------------------------------------
# The gateway image builds the workspace from source on first run; expect
# several minutes before anything is listening.
"${COMPOSE[@]}" up -d --build

# ---------------------------------------------------------------------------
step "Migrating ClickHouse"
# ---------------------------------------------------------------------------
# Run from the host against the published port: these are repo scripts, and the
# operator already has the checkout that the Supabase CLI required.
(cd "$DASHBOARD" && node ./clickhouse/migrate.mjs \
  "--host=http://localhost:${CLICKHOUSE_PORT}" \
  --user=default \
  "--password=${CLICKHOUSE_PASSWORD}" \
  --db=default \
  --migrations-home=./clickhouse/migrations)

# The row-policy read identity is provisioned by script, not migration — the
# policies ship in a migration but the user that logs in with them is
# per-environment.
(cd "$DASHBOARD" && \
  CLICKHOUSE_HOST="http://localhost:${CLICKHOUSE_PORT}" \
  CLICKHOUSE_ADMIN_PASSWORD="${CLICKHOUSE_PASSWORD}" \
  CLICKHOUSE_READ_USER="${CLICKHOUSE_READ_USER}" \
  CLICKHOUSE_READ_PASSWORD="${CLICKHOUSE_READ_PASSWORD}" \
  node ./clickhouse/ensure-read-user.mjs)

# ---------------------------------------------------------------------------
step "Waiting for the gateway"
# ---------------------------------------------------------------------------
for _ in $(seq 1 60); do
  if curl -fsS --max-time 5 "http://127.0.0.1:${GATEWAY_PORT}/health" >/dev/null 2>&1; then
    echo "gateway healthy at http://127.0.0.1:${GATEWAY_PORT}"
    break
  fi
  sleep 2
done
curl -fsS --max-time 5 "http://127.0.0.1:${GATEWAY_PORT}/health" >/dev/null 2>&1 \
  || die "gateway did not become healthy — check '${COMPOSE[*]} logs gateway'"

# ---------------------------------------------------------------------------
step "Next: start the dashboard"
# ---------------------------------------------------------------------------
cat <<EOF

The gateway, ClickHouse, and MinIO are up. The dashboard runs on the host
(docker/README.md explains why). Start it with:

  cd apps/tenant-dashboard
  set -a; . ../../docker/.env.selfhost; set +a
  export DATABASE_URL="\$SUPABASE_DB_URL"
  export NEXT_PUBLIC_SUPABASE_URL="\$SUPABASE_API_URL_FROM_HOST"
  export NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="\$SUPABASE_PUBLISHABLE_KEY"
  export NEXT_PUBLIC_APP_URL="http://localhost:${DASHBOARD_PORT:-3002}"
  export NEXT_PUBLIC_GATEWAY_URL="http://localhost:${GATEWAY_PORT}"
  export NEXT_PUBLIC_API_URL="http://localhost:${GATEWAY_PORT}"
  export CLICKHOUSE_HOST="http://localhost:${CLICKHOUSE_PORT}"
  export OUTERLAYER_SELF_HOSTED=true BILLING_ENABLED=false
  export EMAIL_PROVIDER=smtp SMTP_HOST=localhost SMTP_PORT=2500 EMAIL_ENABLED=false
  export UNKEY_API_KEY=unused-on-self-host CRON_SECRET=unused-on-self-host
  export GITHUB_APP_ID=0 GITHUB_APP_PRIVATE_KEY=unused GITHUB_APP_WEBHOOK_SECRET=unused
  export PORT=${DASHBOARD_PORT:-3002}
  npx next build && npx next start

Export the environment before 'next build', not just before 'next start':
NEXT_PUBLIC_* values are baked into the client bundle at build time.

Then open http://localhost:${DASHBOARD_PORT:-3002} and sign up.

EOF
