// Re-export of the shared generated Supabase types.
//
// The canonical file lives in `@repo/db-types`, regenerated by
// `yarn codegen:db`. This shim exists so existing imports
// (`from '../types/db'`, `from '@/types/db'`, etc.) continue to work
// without a mass rewrite.
export * from '@repo/db-types';
