import { describe, expect, test } from 'vitest';
import { isHarnessOnlySession } from '../trivial-session';
import type { TracePreprocessorSpan } from '../trace-preprocessor';

const span = (
  name: string,
  input: string,
  n: number,
): TracePreprocessorSpan => ({
  id: `s${n}`,
  parentId: 'root',
  name,
  type: 'SPAN',
  timestamp: `2026-07-01 10:00:0${n}.000000000`,
  input,
  output: '',
});

describe('isHarnessOnlySession', () => {
  // The live shape behind the immortal "Local Session Clear" task topic: a
  // caveat turn plus a /clear envelope, nothing typed. Summarized anyway,
  // seventeen of these clustered as the page's fourth-biggest "task".
  test('a /clear-only session is trivial — the exact live shape', () => {
    const spans = [
      span(
        'agent.turn.user',
        '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages…</local-command-caveat>',
        1,
      ),
      span(
        'agent.turn.user',
        '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
        2,
      ),
    ];
    expect(isHarnessOnlySession(spans)).toBe(true);
  });

  test('a session of only relayed peer messages is trivial', () => {
    const spans = [
      span(
        'agent.turn.user',
        'Another Claude session sent a message:\n<teammate-message>{"type":"idle_notification"}</teammate-message>',
        1,
      ),
    ];
    expect(isHarnessOnlySession(spans)).toBe(true);
  });

  test('ANY developer-typed text keeps the session out of the gate — even below steering\'s minimum turn length', () => {
    const spans = [
      span('agent.turn.user', '<command-name>/clear</command-name>', 1),
      span('agent.turn.user', 'fix it', 2),
    ];
    expect(isHarnessOnlySession(spans)).toBe(false);
  });

  test('a greeting/smoke-test turn is NOT gated — the prompt owns judgment calls', () => {
    expect(
      isHarnessOnlySession([span('agent.turn.user', 'hello, are you there?', 1)]),
    ).toBe(false);
  });

  test('a trace with no user-turn spans (plain OTLP) is never trivial', () => {
    const spans = [
      { ...span('llm.generation', 'summarize this document for me', 1), type: 'GENERATION' },
    ];
    expect(isHarnessOnlySession(spans)).toBe(false);
  });

  test('non-string turn input is judged by its JSON form', () => {
    const structured = {
      ...span('agent.turn.user', '', 1),
      input: { role: 'user', content: 'use zod for the new validators' } as unknown as string,
    };
    expect(isHarnessOnlySession([structured])).toBe(false);
  });
});
