/**
 * Generated-file header. Markdown outputs only — JSON has no comment syntax,
 * so `.mcp.json`/`.cursor/mcp.json` never get one; that is a documented
 * limitation, not an oversight. Content is static plus the source path only
 * — no dates, no versions, no environment reads, so emit stays deterministic.
 */
const HEADER_PREFIX = '<!-- generated by OuterLayer from ';
const HEADER_SUFFIX = ' — edit the source, not this file -->\n';

function generatedHeader(sourcePath: string): string {
  return `${HEADER_PREFIX}${sourcePath}${HEADER_SUFFIX}`;
}

/**
 * A YAML frontmatter block must remain the first bytes of the file:
 * frontmatter parsers (Claude Code's skill/command loader, Cursor's rule
 * loader) only recognize the block at line 1, and skill routing reads
 * `description` from it — a header above the delimiter silently breaks
 * discovery. The header therefore lands immediately AFTER the closing
 * delimiter; files without frontmatter keep it at the top.
 */
export function withHeader(sourcePath: string, content: string): string {
  const end = frontmatterEnd(content);
  if (end === undefined) return generatedHeader(sourcePath) + content;
  return content.slice(0, end) + generatedHeader(sourcePath) + content.slice(end);
}

/** Byte offset just past the closing `---` line of a leading frontmatter
 * block, or undefined when the content doesn't open with one. A dangling
 * opener with no closing delimiter is treated as "no frontmatter" — the
 * header goes to the top, which is safe for a file no parser would accept
 * as frontmatter anyway. */
function frontmatterEnd(content: string): number | undefined {
  if (!content.startsWith('---\n')) return undefined;
  const close = content.indexOf('\n---\n', 3);
  if (close === -1) return undefined;
  return close + '\n---\n'.length;
}

/**
 * The source path recorded in a generated file's header, wherever emit
 * placed it (line 1, or immediately after a leading frontmatter block), or
 * undefined for files that don't carry one. The single authority for
 * "is this one of our generated files?" — orphan detection must accept
 * every placement `withHeader` can produce, so both live here.
 */
export function extractGeneratedSource(content: string): string | undefined {
  const positions = [0, frontmatterEnd(content)].filter((p): p is number => p !== undefined);
  for (const pos of positions) {
    const slice = content.slice(pos);
    if (!slice.startsWith(HEADER_PREFIX)) continue;
    const nl = slice.indexOf('\n');
    if (nl === -1) continue;
    const line = slice.slice(0, nl + 1);
    if (!line.endsWith(HEADER_SUFFIX)) continue;
    return line.slice(HEADER_PREFIX.length, line.length - HEADER_SUFFIX.length);
  }
  return undefined;
}
