import { describe, expect, it } from 'vitest';
import { withHeader } from './header';
import { extractGeneratedSource } from './index';

const HEADER = '<!-- generated by OuterLayer from src.md — edit the source, not this file -->\n';

describe('withHeader', () => {
  it('places the header on line 1 for content without frontmatter', () => {
    expect(withHeader('src.md', 'Body.\n')).toBe(HEADER + 'Body.\n');
  });

  it('keeps a leading frontmatter block at byte 0 and inserts the header after its closing delimiter', () => {
    const content = '---\nname: x\ndescription: A skill.\n---\nBody.\n';
    expect(withHeader('src.md', content)).toBe('---\nname: x\ndescription: A skill.\n---\n' + HEADER + 'Body.\n');
  });

  it('treats a dangling frontmatter opener with no closing delimiter as no frontmatter', () => {
    const content = '---\nname: x\nBody with no close.\n';
    expect(withHeader('src.md', content)).toBe(HEADER + content);
  });

  it('does not mistake a mid-file --- ruler for a frontmatter open', () => {
    const content = 'Intro.\n---\nSection.\n';
    expect(withHeader('src.md', content)).toBe(HEADER + content);
  });
});

describe('extractGeneratedSource', () => {
  it('reads the source path from a line-1 header', () => {
    expect(extractGeneratedSource(HEADER + 'Body.\n')).toBe('src.md');
  });

  it('reads the source path from a header placed after a frontmatter block', () => {
    const content = '---\nname: x\n---\n' + HEADER + 'Body.\n';
    expect(extractGeneratedSource(content)).toBe('src.md');
  });

  it('returns undefined for files without a header', () => {
    expect(extractGeneratedSource('---\nname: x\n---\nBody.\n')).toBeUndefined();
    expect(extractGeneratedSource('Plain file.\n')).toBeUndefined();
  });

  it('round-trips every placement withHeader produces', () => {
    for (const content of ['Body.\n', '---\nname: x\n---\nBody.\n']) {
      expect(extractGeneratedSource(withHeader('a/b.md', content))).toBe('a/b.md');
    }
  });
});
