/**
 * Generated-file header. Markdown outputs only — JSON has no comment syntax,
 * so `.mcp.json`/`.cursor/mcp.json` never get one; that is a documented
 * limitation, not an oversight. Content is static plus the source path only
 * — no dates, no versions, no environment reads, so emit stays deterministic.
 *
 * Placement: BELOW a leading frontmatter block, on line one otherwise.
 * Consumers (Claude Code, Cursor) only recognize frontmatter when the file's
 * first bytes are the opening `---`; a comment above it makes the whole block
 * read as body and erases the output's name/description.
 */
import { splitRawFile } from '../frontmatter/parse';

const HEADER_OPEN = '<!-- generated by OuterLayer from ';
const HEADER_CLOSE = ' — edit the source, not this file -->\n';

function generatedHeader(sourcePath: string): string {
  return `${HEADER_OPEN}${sourcePath}${HEADER_CLOSE}`;
}

export function withHeader(sourcePath: string, content: string): string {
  const { frontmatterInner, body } = splitRawFile(content);
  if (frontmatterInner === null) return generatedHeader(sourcePath) + content;
  // Everything before the body is the frontmatter block, delimiters included.
  const block = content.slice(0, content.length - body.length);
  // A block whose closing `---` sits at EOF carries no trailing newline.
  const separator = block.endsWith('\n') ? '' : '\n';
  return block + separator + generatedHeader(sourcePath) + body;
}

/**
 * The detection inverse of `withHeader` for `--check` orphan scanning: the
 * source path a generated file names, or null when no header sits in either
 * sanctioned position (line one, or the first line after a leading
 * frontmatter block). Positions are strict so a file that merely mentions the
 * header text mid-body is never mistaken for a generated one.
 */
export function generatedHeaderSource(content: string): string | null {
  const atStart = headerSourceAt(content);
  if (atStart !== null) return atStart;
  const { frontmatterInner, body } = splitRawFile(content);
  if (frontmatterInner === null) return null;
  return headerSourceAt(body);
}

function headerSourceAt(text: string): string | null {
  if (!text.startsWith(HEADER_OPEN)) return null;
  const end = text.indexOf(HEADER_CLOSE, HEADER_OPEN.length);
  if (end === -1) return null;
  const sourcePath = text.slice(HEADER_OPEN.length, end);
  return sourcePath.includes('\n') ? null : sourcePath;
}
