import { describe, expect, it } from 'vitest';
import { generatedHeaderSource, withHeader } from './header';

const HEADER = '<!-- generated by OuterLayer from src/a.md — edit the source, not this file -->\n';

describe('withHeader', () => {
  it('puts the header on line one of frontmatter-free content', () => {
    expect(withHeader('src/a.md', 'Body.\n')).toBe(`${HEADER}Body.\n`);
  });

  it('puts the header below a leading frontmatter block, byte-exact', () => {
    expect(withHeader('src/a.md', '---\nname: a\n---\nBody.\n')).toBe(
      `---\nname: a\n---\n${HEADER}Body.\n`,
    );
  });

  it('handles an empty frontmatter block', () => {
    expect(withHeader('src/a.md', '---\n---\nBody.\n')).toBe(`---\n---\n${HEADER}Body.\n`);
  });

  it('starts the header on its own line when the closing delimiter sits at EOF without a newline', () => {
    expect(withHeader('src/a.md', '---\nname: a\n---')).toBe(`---\nname: a\n---\n${HEADER}`);
  });

  it('keeps CRLF frontmatter intact and inserts the header after it', () => {
    expect(withHeader('src/a.md', '---\r\nname: a\r\n---\r\nBody.\r\n')).toBe(
      `---\r\nname: a\r\n---\r\n${HEADER}Body.\r\n`,
    );
  });

  it('treats a leading --- with no closing delimiter as body, header on line one', () => {
    expect(withHeader('src/a.md', '---\nnot frontmatter\n')).toBe(`${HEADER}---\nnot frontmatter\n`);
  });
});

describe('generatedHeaderSource', () => {
  it('reads the source path from a line-one header', () => {
    expect(generatedHeaderSource(`${HEADER}Body.\n`)).toBe('src/a.md');
  });

  it('reads the source path from a header below frontmatter', () => {
    expect(generatedHeaderSource(`---\nname: a\n---\n${HEADER}Body.\n`)).toBe('src/a.md');
  });

  it('still recognizes the legacy placement above frontmatter', () => {
    expect(generatedHeaderSource(`${HEADER}---\nname: a\n---\nBody.\n`)).toBe('src/a.md');
  });

  it('returns null when the header text only appears mid-body', () => {
    expect(generatedHeaderSource(`Intro.\n${HEADER}`)).toBe(null);
    expect(generatedHeaderSource(`---\nname: a\n---\nIntro.\n${HEADER}`)).toBe(null);
  });

  it('returns null for an unterminated header or a path spanning lines', () => {
    expect(generatedHeaderSource('<!-- generated by OuterLayer from src/a.md\nBody.\n')).toBe(null);
    expect(
      generatedHeaderSource('<!-- generated by OuterLayer from src/\na.md — edit the source, not this file -->\n'),
    ).toBe(null);
  });

  it('returns null for plain content with no header anywhere', () => {
    expect(generatedHeaderSource('Body.\n')).toBe(null);
    expect(generatedHeaderSource('---\nname: a\n---\nBody.\n')).toBe(null);
  });
});
