/**
 * Generated-file header. Markdown outputs only — JSON has no comment syntax,
 * so `.mcp.json`/`.cursor/mcp.json` never get one; that is a documented
 * limitation, not an oversight. Content is static plus the source path only
 * — no dates, no versions, no environment reads, so emit stays deterministic.
 */
function generatedHeader(sourcePath: string): string {
  return `<!-- generated by OuterLayer from ${sourcePath} — edit the source, not this file -->\n`;
}

export function withHeader(sourcePath: string, content: string): string {
  return generatedHeader(sourcePath) + content;
}
