import { describe, expect, it } from 'vitest';
import { emitTree, mergeEmitResults } from './index';
import { fixtureInput } from './test-fixture';
import type { TargetBuildResult } from './types';

describe('emitTree — determinism', () => {
  it('produces deep-equal AND serialized-JSON-byte-equal results across two calls over the same input', () => {
    const input = fixtureInput(['claude-code', 'cursor', 'codex']);

    const first = emitTree(input);
    const second = emitTree(input);

    expect(first).toEqual(second);
    expect(JSON.stringify(first)).toBe(JSON.stringify(second));
  });
});

describe('mergeEmitResults — conflict + dedup', () => {
  it('reports a single path_conflict error and writes no file when two targets emit different content at the same path', () => {
    const a: TargetBuildResult = { files: [{ path: 'AGENTS.md', content: 'from target A\n' }], copies: [], warnings: [] };
    const b: TargetBuildResult = { files: [{ path: 'AGENTS.md', content: 'from target B\n' }], copies: [], warnings: [] };

    const result = mergeEmitResults([a, b]);

    expect(result.files).toEqual([]);
    expect(result.errors).toEqual([
      { path: 'AGENTS.md', code: 'path_conflict', message: 'multiple targets emit different content at "AGENTS.md" — no file written' },
    ]);
  });

  it('reports a single path_conflict error and copies nothing when two targets copy different sources to the same path', () => {
    const a: TargetBuildResult = { files: [], copies: [{ toPath: 'assets/logo.png', fromSourcePath: 'skills/x/logo.png' }], warnings: [] };
    const b: TargetBuildResult = { files: [], copies: [{ toPath: 'assets/logo.png', fromSourcePath: 'skills/y/logo.png' }], warnings: [] };

    const result = mergeEmitResults([a, b]);

    expect(result.copies).toEqual([]);
    expect(result.errors).toEqual([
      { path: 'assets/logo.png', code: 'path_conflict', message: 'multiple targets copy different sources to "assets/logo.png" — no file copied' },
    ]);
  });

  it('dedups identical content at the same path into a single file, with no error — the AGENTS.md-sharing case', () => {
    const a: TargetBuildResult = { files: [{ path: 'AGENTS.md', content: 'shared\n' }], copies: [], warnings: [] };
    const b: TargetBuildResult = { files: [{ path: 'AGENTS.md', content: 'shared\n' }], copies: [], warnings: [] };
    const c: TargetBuildResult = { files: [{ path: 'AGENTS.md', content: 'shared\n' }], copies: [], warnings: [] };

    const result = mergeEmitResults([a, b, c]);

    expect(result.errors).toEqual([]);
    expect(result.files).toEqual([{ path: 'AGENTS.md', content: 'shared\n' }]);
  });
});

describe('emitTree — cross-target AGENTS.md dedup', () => {
  it('emits exactly one root AGENTS.md entry when both cursor and copilot are enabled', () => {
    const result = emitTree(fixtureInput(['cursor', 'copilot']));

    const rootAgentsMd = result.files.filter((f) => f.path === 'AGENTS.md');
    expect(rootAgentsMd).toHaveLength(1);
    expect(rootAgentsMd[0]).toEqual({
      path: 'AGENTS.md',
      content: '<!-- generated by OuterLayer from .outerlayer/AGENTS.md — edit the source, not this file -->\nRoot instructions.\n',
    });
    expect(result.errors).toEqual([]);
  });
});

describe('emitTree — targets guard', () => {
  it('returns a no_targets error and emits nothing when targets is empty', () => {
    const result = emitTree(fixtureInput([]));

    expect(result.files).toEqual([]);
    expect(result.copies).toEqual([]);
    expect(result.warnings).toEqual([]);
    expect(result.errors).toEqual([
      { path: 'targets', code: 'no_targets', message: 'no targets configured — nothing to emit' },
    ]);
  });
});

describe('emitTree — external-instructions is never a source', () => {
  it('never emits content derived from a root-external CLAUDE.md, for any target', () => {
    const result = emitTree(fixtureInput(['claude-code', 'cursor', 'codex', 'copilot', 'factory']));

    for (const file of result.files) {
      expect(file.content).not.toContain('Legacy');
    }
  });
});
