// Re-export of the shared generated Supabase types.
//
// The canonical file lives in `@repo/db-types`, regenerated by
// `yarn codegen:db` (run from apps/tenant-dashboard). This shim exists
// so existing relative imports (`from '../db'`, `from '../../db'`, etc.)
// continue to work without a mass rewrite.
export * from '@repo/db-types';
