// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Magu Studios, Inc.

/**
 * `outerlayer emit`: reads a repo's `.outerlayer/` tree,
 * classifies it, and compiles it into the native files each target tool
 * configured in `.outerlayer/config.json` actually reads (Claude Code,
 * Cursor, Codex, Copilot, Factory) — the compile-out half of the format.
 * `--check` is the CI half: it computes the same outputs and compares them
 * against disk instead of writing, so drift can gate a PR the same way
 * `tsc --noEmit` does.
 *
 * Target selection comes from `.outerlayer/config.json` ONLY — there is no
 * `--target` flag or env override. A repo with no config (or an empty
 * `targets` array) gets no emit, by design: the format is self-describing,
 * not defaulted.
 *
 * All I/O lives here — `@outerlayer/context-format`'s `emitTree` stays pure
 * (scope guard, no fs): this command reads the config, walks the tree,
 * classifies it, reads content-kind file contents, and writes (or, under
 * `--check`, compares) what `emitTree` computes.
 */
import { existsSync, copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import {
  classifyTree,
  emitTree,
  normalizePath,
  parseOuterlayerConfig,
  type EmitCopy,
  type EmitInput,
  type EmitResult,
  type FieldIssue,
  type TargetId,
} from "@outerlayer/context-format";

/** Kinds `emitTree`'s target builders actually read source content for — `reference`
 * and `subagent` are classified but not emitted by any v1 target,
 * and `external-instructions` is a target-only marker, never a source. */
const CONTENT_KINDS = new Set(["instructions", "skill", "skill-reference", "command", "mcp"]);
const SKIP_DIRS = new Set(["node_modules", ".git"]);

/** Must match emit/header.ts's `generatedHeader` exactly — the signal `--check`
 * uses to tell "one of our generated files" from a user's own file at the same
 * path. JSON targets (`.mcp.json`/`.cursor/mcp.json`) carry no header (JSON has
 * no comment syntax) and so can never be orphan-detected. */
const HEADER_PREFIX_RE = /^<!-- generated by OuterLayer from (.+) — edit the source, not this file -->\n/;

/** The one refusal message for "no usable target set" — a missing config file
 * and an explicit `targets: []` are the same underlying problem (nothing to
 * emit), so both produce this exact text (CLI acceptance (b)/(c)). */
const NO_CONFIG_MESSAGE =
  'no .outerlayer/config.json with a non-empty targets array — create one, e.g. {"targets": ["claude-code"]}';

const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const DIM = "\x1b[2m";
const RESET = "\x1b[0m";

export class EmitError extends Error {}

export interface EmitCommandOptions {
  /** Repo root to read from (default: `process.cwd()`). */
  cwd?: string;
  /** Compute outputs and compare against disk; write nothing, exit 1 on any
   * drift. Orphan detection is scoped to header-carrying outputs only. */
  check?: boolean;
  /** Suppress stdout/stderr writes (tests). */
  quiet?: boolean;
  /** Machine-readable output. */
  json?: boolean;
}

type DriftKind = "missing" | "content" | "orphaned";

interface DriftEntry {
  kind: DriftKind;
  path: string;
}

export interface EmitCommandResult {
  targets: TargetId[];
  /** Repo-relative paths written, sorted (mirrors `EmitResult.files` order).
   * Empty under `--check` (nothing is ever written in that mode). */
  files: string[];
  /** Repo-relative destination paths byte-copied, sorted. Empty under `--check`. */
  copies: string[];
  warnings: FieldIssue[];
  errors: FieldIssue[];
  /** `--check` only: present (possibly empty) whenever `opts.check` is true. */
  drift?: DriftEntry[];
  output: string;
  exitCode: 0 | 1;
}

/** Reads and validates `.outerlayer/config.json` — the single source of target
 * selection; there is no `--target` flag. A missing file and
 * an explicit `no_targets` refusal collapse to the same actionable message;
 * any other validation failure (malformed JSON, unknown target id) surfaces
 * `parseOuterlayerConfig`'s specific field errors instead, since the file DOES
 * exist and isn't simply "no config" in that case. */
function resolveTargetsFromConfig(repoRoot: string): TargetId[] {
  const configPath = join(repoRoot, ".outerlayer", "config.json");
  if (!existsSync(configPath)) throw new EmitError(NO_CONFIG_MESSAGE);

  const raw = readFileSync(configPath, "utf8");
  const result = parseOuterlayerConfig(raw);
  if (result.ok) return result.config!.targets;

  if (result.errors.some((e) => e.code === "no_targets")) throw new EmitError(NO_CONFIG_MESSAGE);

  const detail = result.errors.map((e) => `${e.path}: ${e.message}`).join("; ");
  throw new EmitError(`invalid .outerlayer/config.json — ${detail}`);
}

function toRepoRelative(repoRoot: string, absPath: string): string {
  return normalizePath(relative(repoRoot, absPath).split(sep).join("/"));
}

/** Recursively collects every file under any `.outerlayer/` directory, skipping
 * `node_modules`/`.git` elsewhere in the tree. Sorted for deterministic input
 * to `classifyTree` (emit's own merge step re-sorts its output regardless). */
function discoverOuterlayerPaths(repoRoot: string): string[] {
  const out: string[] = [];
  walk(repoRoot, repoRoot, false, out);
  return out.sort();
}

function walk(dir: string, repoRoot: string, insideOuterlayer: boolean, out: string[]): void {
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!insideOuterlayer && SKIP_DIRS.has(entry.name)) continue;
      walk(full, repoRoot, insideOuterlayer || entry.name === ".outerlayer", out);
    } else if (entry.isFile() && insideOuterlayer) {
      out.push(toRepoRelative(repoRoot, full));
    }
  }
}

/** Reads the tree and assembles `EmitInput` — the CLI-side half of the emit
 * port (emit/types.ts): `classifyTree` for `entries`, content-kind file reads for
 * `contents`, and everything classification excluded (skill assets/scripts) for
 * `assetPaths`. Target builders silently ignore any path here that doesn't fit
 * a skill-asset shape, so a superset is safe. `sourcePaths` (every classified
 * entry's path, regardless of target selection) is `--check`'s signal for
 * "this source still exists" — orphan detection needs it independent of the
 * configured target set. */
function buildEmitInput(repoRoot: string, targets: TargetId[]): { input: EmitInput; sourcePaths: Set<string> } {
  const discovered = discoverOuterlayerPaths(repoRoot);
  const { entries } = classifyTree(discovered);
  const classified = new Set(entries.map((e) => e.path));

  const contents = new Map<string, string>();
  for (const entry of entries) {
    if (!CONTENT_KINDS.has(entry.kind)) continue;
    contents.set(entry.path, readFileSync(join(repoRoot, entry.path), "utf8"));
  }

  const assetPaths = discovered.filter((p) => !classified.has(p));
  return { input: { entries, contents, assetPaths, targets }, sourcePaths: classified };
}

function writeOutputs(repoRoot: string, result: EmitResult): { files: string[]; copies: string[] } {
  const files: string[] = [];
  for (const file of result.files) {
    const abs = join(repoRoot, file.path);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, file.content);
    files.push(file.path);
  }
  const copies: string[] = [];
  for (const copy of result.copies) {
    const abs = join(repoRoot, copy.toPath);
    mkdirSync(dirname(abs), { recursive: true });
    copyFileSync(join(repoRoot, copy.fromSourcePath), abs);
    copies.push(copy.toPath);
  }
  return { files, copies };
}

function renderSuccess(targets: TargetId[], files: string[], copies: string[]): string {
  const copySuffix = copies.length > 0 ? `, ${copies.length} ${copies.length === 1 ? "copy" : "copies"}` : "";
  return `${GREEN}✓${RESET} emitted ${files.length} file${files.length === 1 ? "" : "s"}${copySuffix} for ${DIM}${targets.join(", ")}${RESET}`;
}

function renderFailure(errors: FieldIssue[]): string {
  const lines = [`${RED}✗${RESET} emit failed — nothing written`];
  for (const e of errors) lines.push(`  ${RED}✗${RESET} ${e.path}: ${e.message}`);
  return lines.join("\n");
}

function renderCheck(targets: TargetId[], drift: DriftEntry[]): string {
  if (drift.length === 0) return `${GREEN}✓${RESET} up to date for ${DIM}${targets.join(", ")}${RESET}`;
  const lines = [`${RED}✗${RESET} drift detected (${drift.length}) — run \`outerlayer emit\` to update`];
  for (const d of drift) lines.push(`  ${RED}✗${RESET} ${d.kind.padEnd(8)} ${d.path}`);
  return lines.join("\n");
}

/** Missing or content-mismatched against `expectedContent` — a headerless file
 * that happens to already sit at a would-be output path (a genuine user file)
 * is content drift like any other; `--check` never overwrites it, it only
 * reports it (this function never touches disk). */
function compareFile(repoRoot: string, path: string, expectedContent: string): DriftEntry | undefined {
  const abs = join(repoRoot, path);
  if (!existsSync(abs)) return { kind: "missing", path };
  if (readFileSync(abs, "utf8") !== expectedContent) return { kind: "content", path };
  return undefined;
}

/** Byte-for-byte compare (copies may be binary assets, so no text decoding). */
function compareCopy(repoRoot: string, copy: EmitCopy): DriftEntry | undefined {
  const abs = join(repoRoot, copy.toPath);
  if (!existsSync(abs)) return { kind: "missing", path: copy.toPath };
  if (!readFileSync(abs).equals(readFileSync(join(repoRoot, copy.fromSourcePath)))) {
    return { kind: "content", path: copy.toPath };
  }
  return undefined;
}

/** Every file in the tree (skipping `node_modules`/`.git`, and `.outerlayer`
 * itself — sources never carry the header). Reused for orphan scanning. */
function discoverAllFiles(repoRoot: string): string[] {
  const out: string[] = [];
  walkAll(repoRoot, repoRoot, out);
  return out;
}

function walkAll(dir: string, repoRoot: string, out: string[]): void {
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name) || entry.name === ".outerlayer") continue;
      walkAll(full, repoRoot, out);
    } else if (entry.isFile()) {
      out.push(toRepoRelative(repoRoot, full));
    }
  }
}

/** A header-carrying file not in this run's computed output is only "orphaned"
 * (source no longer emits it) when its named source is truly gone from
 * classification — not merely because a narrower `targets` config than a
 * previous `emit` run used excludes it. */
function findOrphans(repoRoot: string, computedFiles: ReadonlySet<string>, sourcePaths: ReadonlySet<string>): DriftEntry[] {
  const orphans: DriftEntry[] = [];
  for (const path of discoverAllFiles(repoRoot)) {
    if (computedFiles.has(path)) continue;
    let content: string;
    try {
      content = readFileSync(join(repoRoot, path), "utf8");
    } catch {
      continue;
    }
    const match = HEADER_PREFIX_RE.exec(content);
    if (!match) continue;
    const sourcePath = match[1]!;
    if (!sourcePaths.has(sourcePath)) orphans.push({ kind: "orphaned", path });
  }
  return orphans;
}

export function runEmit(opts: EmitCommandOptions = {}): EmitCommandResult {
  const cwd = opts.cwd ?? process.cwd();
  if (!existsSync(cwd)) throw new EmitError(`no such directory: ${cwd}`);

  const targets = resolveTargetsFromConfig(cwd);
  const built = buildEmitInput(cwd, targets);

  const result = emitTree(built.input);
  const hasErrors = result.errors.length > 0;

  if (opts.check) return runCheck(cwd, opts, targets, result, hasErrors, built.sourcePaths);

  const written = hasErrors ? { files: [], copies: [] } : writeOutputs(cwd, result);

  const exitCode: 0 | 1 = hasErrors ? 1 : 0;
  const output = opts.json
    ? JSON.stringify({ targets, files: written.files, copies: written.copies, warnings: result.warnings, errors: result.errors })
    : hasErrors
      ? renderFailure(result.errors)
      : renderSuccess(targets, written.files, written.copies);

  if (!opts.quiet) {
    if (opts.json) {
      process.stdout.write(output + "\n");
    } else if (hasErrors) {
      process.stderr.write(output + "\n");
    } else {
      process.stdout.write(output + "\n");
      for (const w of result.warnings) process.stderr.write(`  ${YELLOW}!${RESET} ${w.path}: ${w.message}\n`);
    }
  }

  return { targets, files: written.files, copies: written.copies, warnings: result.warnings, errors: result.errors, output, exitCode };
}

function runCheck(
  cwd: string,
  opts: EmitCommandOptions,
  targets: TargetId[],
  result: EmitResult,
  hasErrors: boolean,
  sourcePaths: Set<string>,
): EmitCommandResult {
  const drift: DriftEntry[] = [];
  if (!hasErrors) {
    const computedFiles = new Set(result.files.map((f) => f.path));
    for (const file of result.files) {
      const d = compareFile(cwd, file.path, file.content);
      if (d) drift.push(d);
    }
    for (const copy of result.copies) {
      const d = compareCopy(cwd, copy);
      if (d) drift.push(d);
    }
    drift.push(...findOrphans(cwd, computedFiles, sourcePaths));
    drift.sort((a, b) => a.path.localeCompare(b.path) || a.kind.localeCompare(b.kind));
  }

  const exitCode: 0 | 1 = hasErrors || drift.length > 0 ? 1 : 0;
  const output = opts.json
    ? JSON.stringify({ targets, drift, warnings: result.warnings, errors: result.errors })
    : hasErrors
      ? renderFailure(result.errors)
      : renderCheck(targets, drift);

  if (!opts.quiet) {
    if (opts.json) {
      process.stdout.write(output + "\n");
    } else if (hasErrors || drift.length > 0) {
      process.stderr.write(output + "\n");
    } else {
      process.stdout.write(output + "\n");
      for (const w of result.warnings) process.stderr.write(`  ${YELLOW}!${RESET} ${w.path}: ${w.message}\n`);
    }
  }

  return { targets, files: [], copies: [], warnings: result.warnings, errors: result.errors, drift, output, exitCode };
}
