-- =============================================================================
-- Connector-Token PostgREST Confinement
-- =============================================================================
-- Purpose: Supabase's OAuth 2.1 server mints a connector's access token
--   (claude.ai / ChatGPT custom-connector, or any RFC-compliant MCP client
--   that completed DCR + authorize + token) as an ordinary `role:
--   authenticated` user JWT, distinguished only by a `client_id` claim —
--   Supabase does not enforce OAuth scopes. The gateway confines these
--   tokens to the MCP mount (`allowConnectorToken`, see
--   packages/gateway-core/src/lib/verify-bearer.ts), but that confinement
--   lives entirely in application code: nothing stops a leaked connector
--   token from being replayed directly against `/rest/v1/*` with the full
--   power of the `authenticated` role the approving user holds.
--
-- Fix: a RESTRICTIVE policy — `USING (NOT private.is_connector_token())` —
--   on every table `authenticated` is explicitly granted access to in the
--   schema files, EXCEPT the six named below. Restrictive policies AND with
--   a table's existing permissive policies (never OR), so this is purely
--   additive: it can only narrow what a connector token sees, and has no
--   effect on a session JWT without a `client_id` claim
--   (`is_connector_token()` is false for those, so `NOT ...` is true and
--   every existing policy governs exactly as before).
--
-- Table list is a hand-verified, explicit enumeration rather than a live
--   catalog scan (e.g. looping over `information_schema.role_table_grants`).
--   A local Supabase project can carry legacy default grants that predate a
--   schema tightening — `db diff` compares this file against a database
--   built ONLY from the schema files, so any policy this file generated by
--   inspecting a possibly-drifted live catalog would silently disagree with
--   that clean rebuild. An explicit list has no such dependency: it matches
--   whatever `db diff` builds, in any environment, always.
--
-- Exemptions — tables a connector token still needs to READ, because the
--   gateway's own MCP tool handlers read them via the caller's forwarded JWT
--   (`getScopedSupabase` in packages/gateway-core/src/openapi/routes/
--   _shared.ts, bearer branch). Each is already gated by the SAME RLS an
--   ordinary signed-in dashboard user faces for that table — a leaked
--   connector token gains no read access beyond what ties directly to the
--   MCP surface the user already approved. No MCP tool handler writes to any
--   of these tables, so the exemption is SELECT-only: a separate RESTRICTIVE
--   block below denies INSERT/UPDATE/DELETE from a connector token on all
--   six, same as every other table in this file:
--     * membership         — resolveMembershipId / buildActorNameResolver
--                             (sessions.ts): the caller's own membership
--                             row, or teammates' rows gated by the
--                             existing `membership.read`-or-self policy.
--     * profile             — buildActorNameResolver (sessions.ts): display
--                             names for actor ids already resolved via the
--                             gated membership read above.
--     * environment          — resolveTopicsScope (topics.ts): the app's
--                             default environment name, tenant-scoped.
--     * context_snapshot     — listContextChanges (context.ts): synced-
--                             commit history, app-scoped.
--     * pull_request         — buildPrOutcomeReader (pr-outcomes.ts, via
--     * pull_request_session   sessions.ts buildPorts): PR/session
--                             reconciliation links, gated by the existing
--                             `git_connection.read`-permission policy —
--                             NOT a bare tenant scope, so reproducing it
--                             under a different role would duplicate the
--                             permission-set logic `private.
--                             effective_app_permissions` already owns as
--                             its single source of truth. Exempting here
--                             keeps that logic in one place.
--   Every other table a connector token could reach today — billing,
--   api_key, tenant, sso_config, audit_log, custom_role, and the rest —
--   is fully confined: a connector token gets zero rows. A connector token
--   gains nothing beyond the MCP read surface: on the six exempted tables it
--   reads under the same RLS a signed-in user faces, and on every table
--   (exempted or not) it cannot INSERT, UPDATE, or DELETE a single row.
--
-- Keeping this list in sync: adding a new `GRANT ... TO authenticated` in
--   any schema file needs a matching line here (or a documented addition to
--   the exemption list above). `db diff` does NOT catch an omission — a
--   table missing its RESTRICTIVE policy is, from a clean rebuild's
--   perspective, simply a table that never had one; there is no prior state
--   for it to drift against, so the omission is invisible to schema/migration
--   diffing. `pr_session_comment` reached main exactly this way: its schema
--   file was added in parallel with this one and neither PR's diff showed
--   anything wrong. The catalog-driven test in
--   apps/integration-tests/src/tests/connector-token-confinement.test.ts
--   (enumerating `information_schema.role_table_grants` for `authenticated`
--   against a live database and asserting every granted table carries a
--   `connector_token_*` policy or sits on the exemption list above) is what
--   actually catches this class of omission.
--
-- Dependencies: 01a-private-authz.sql (private.is_connector_token), every
--   table-creating schema file (this must sort after all of them — see
--   config.toml schema_paths, which governs load order, not the filename).
-- =============================================================================

CREATE POLICY connector_token_confinement ON public.tenant                        AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.role_permissions              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.platform_role_permissions     AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.platform_user_role            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.app                          AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.env_var                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.terms_agreement               AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.api_key                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.billing                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.dashboard                     AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.dashboard_widget              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.custom_role                   AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.custom_role_permission        AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.user_git_identity             AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.git_connection                AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.git_branch                    AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_blob                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_tree_entry            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_head                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_sync_event            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.temp_access_grant             AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.tenant_entitlement_override   AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.audit_log                     AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.notification                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.feature_flag                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.feature_flag_override         AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.sso_config                    AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.sso_identity                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.sso_audit_log                 AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.app_member_role               AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.saved_trace_filters           AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.worker_run                    AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.worker_run_event              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.worker_workspace              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.ai_cost_config                AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.pr_session_comment            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.pr_evidence_evaluation         AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.artifact                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());

-- SELECT-exempt tables above still deny writes: a connector token reads
-- membership/profile/environment/context_snapshot/pull_request/
-- pull_request_session under ordinary RLS (see the exemption note above),
-- but FOR ALL can't be split into "SELECT permissive, everything else
-- restrictive" in one policy — a RESTRICTIVE USING clause governs SELECT
-- too. Three narrower policies per table cover INSERT/UPDATE/DELETE only.
CREATE POLICY connector_token_write_confinement ON public.membership              AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_update_confinement ON public.membership             AS RESTRICTIVE FOR UPDATE TO authenticated USING (NOT private.is_connector_token()) WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_delete_confinement ON public.membership             AS RESTRICTIVE FOR DELETE TO authenticated USING (NOT private.is_connector_token());

CREATE POLICY connector_token_write_confinement ON public.profile                 AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_update_confinement ON public.profile                AS RESTRICTIVE FOR UPDATE TO authenticated USING (NOT private.is_connector_token()) WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_delete_confinement ON public.profile                AS RESTRICTIVE FOR DELETE TO authenticated USING (NOT private.is_connector_token());

CREATE POLICY connector_token_write_confinement ON public.environment             AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_update_confinement ON public.environment            AS RESTRICTIVE FOR UPDATE TO authenticated USING (NOT private.is_connector_token()) WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_delete_confinement ON public.environment            AS RESTRICTIVE FOR DELETE TO authenticated USING (NOT private.is_connector_token());

CREATE POLICY connector_token_write_confinement ON public.context_snapshot        AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_update_confinement ON public.context_snapshot       AS RESTRICTIVE FOR UPDATE TO authenticated USING (NOT private.is_connector_token()) WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_delete_confinement ON public.context_snapshot       AS RESTRICTIVE FOR DELETE TO authenticated USING (NOT private.is_connector_token());

CREATE POLICY connector_token_write_confinement ON public.pull_request            AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_update_confinement ON public.pull_request           AS RESTRICTIVE FOR UPDATE TO authenticated USING (NOT private.is_connector_token()) WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_delete_confinement ON public.pull_request           AS RESTRICTIVE FOR DELETE TO authenticated USING (NOT private.is_connector_token());

CREATE POLICY connector_token_write_confinement ON public.pull_request_session    AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_update_confinement ON public.pull_request_session   AS RESTRICTIVE FOR UPDATE TO authenticated USING (NOT private.is_connector_token()) WITH CHECK (NOT private.is_connector_token());
CREATE POLICY connector_token_delete_confinement ON public.pull_request_session   AS RESTRICTIVE FOR DELETE TO authenticated USING (NOT private.is_connector_token());
