-- =============================================================================
-- Connector-Token PostgREST Confinement
-- =============================================================================
-- Purpose: Supabase's OAuth 2.1 server mints a connector's access token
--   (claude.ai / ChatGPT custom-connector, or any RFC-compliant MCP client
--   that completed DCR + authorize + token) as an ordinary `role:
--   authenticated` user JWT, distinguished only by a `client_id` claim —
--   Supabase does not enforce OAuth scopes. The gateway confines these
--   tokens to the MCP mount (`allowConnectorToken`, see
--   packages/gateway-core/src/lib/verify-bearer.ts), but that confinement
--   lives entirely in application code: nothing stops a leaked connector
--   token from being replayed directly against `/rest/v1/*` with the full
--   power of the `authenticated` role the approving user holds.
--
-- Fix: a RESTRICTIVE policy — `USING (NOT private.is_connector_token())` —
--   on every table `authenticated` is explicitly granted access to in the
--   schema files, EXCEPT the six named below. Restrictive policies AND with
--   a table's existing permissive policies (never OR), so this is purely
--   additive: it can only narrow what a connector token sees, and has no
--   effect on a session JWT without a `client_id` claim
--   (`is_connector_token()` is false for those, so `NOT ...` is true and
--   every existing policy governs exactly as before).
--
-- Table list is a hand-verified, explicit enumeration rather than a live
--   catalog scan (e.g. looping over `information_schema.role_table_grants`).
--   A local Supabase project can carry legacy default grants that predate a
--   schema tightening — `db diff` compares this file against a database
--   built ONLY from the schema files, so any policy this file generated by
--   inspecting a possibly-drifted live catalog would silently disagree with
--   that clean rebuild. An explicit list has no such dependency: it matches
--   whatever `db diff` builds, in any environment, always.
--
-- Exemptions — tables a connector token still needs, because the gateway's
--   own MCP tool handlers read them via the caller's forwarded JWT
--   (`getScopedSupabase` in packages/gateway-core/src/openapi/routes/
--   _shared.ts, bearer branch). Each is already gated by the SAME RLS an
--   ordinary signed-in dashboard user faces for that table — a leaked
--   connector token gains no access beyond what ties directly to the
--   MCP surface the user already approved:
--     * membership         — resolveMembershipId / buildActorNameResolver
--                             (sessions.ts): the caller's own membership
--                             row, or teammates' rows gated by the
--                             existing `membership.read`-or-self policy.
--     * profile             — buildActorNameResolver (sessions.ts): display
--                             names for actor ids already resolved via the
--                             gated membership read above.
--     * environment          — resolveTopicsScope (topics.ts): the app's
--                             default environment name, tenant-scoped.
--     * context_snapshot     — listContextChanges (context.ts): synced-
--                             commit history, app-scoped.
--     * pull_request         — buildPrOutcomeReader (pr-outcomes.ts, via
--     * pull_request_session   sessions.ts buildPorts): PR/session
--                             reconciliation links, gated by the existing
--                             `git_connection.read`-permission policy —
--                             NOT a bare tenant scope, so reproducing it
--                             under a different role would duplicate the
--                             permission-set logic `private.
--                             effective_app_permissions` already owns as
--                             its single source of truth. Exempting here
--                             keeps that logic in one place.
--   Every other table a connector token could reach today — billing,
--   api_key, tenant, sso_config, audit_log, custom_role, and the rest —
--   is fully confined: a connector token gets zero rows.
--
-- Keeping this list in sync: adding a new `GRANT ... TO authenticated` in
--   any schema file needs a matching line here (or a documented addition to
--   the exemption list above) — `db diff` catches an omission as drift
--   (the fresh table would have no RESTRICTIVE policy, same as any other
--   missed policy would show up as an unexpected grant/policy diff).
--
-- Dependencies: 01a-private-authz.sql (private.is_connector_token), every
--   table-creating schema file (this must sort after all of them — see
--   config.toml schema_paths, which governs load order, not the filename).
-- =============================================================================

CREATE POLICY connector_token_confinement ON public.tenant                        AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.role_permissions              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.platform_role_permissions     AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.platform_user_role            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.app                          AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.env_var                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.terms_agreement               AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.api_key                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.billing                       AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.dashboard                     AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.dashboard_widget              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.custom_role                   AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.custom_role_permission        AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.user_git_identity             AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.git_connection                AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.git_branch                    AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_blob                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_tree_entry            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_head                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.context_sync_event            AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.temp_access_grant             AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.tenant_entitlement_override   AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.audit_log                     AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.notification                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.feature_flag                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.feature_flag_override         AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.sso_config                    AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.sso_identity                  AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.sso_audit_log                 AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.app_member_role               AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.saved_trace_filters           AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.worker_run                    AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.worker_run_event              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.worker_workspace              AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
CREATE POLICY connector_token_confinement ON public.ai_cost_config                AS RESTRICTIVE FOR ALL TO authenticated USING (NOT private.is_connector_token());
