// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Magu Studios, Inc.

import { describe, expect, it, beforeEach, afterEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { runEmit, EmitError } from "../emit-cmd.js";

let root: string;

/** Matches emit/header.ts's `generatedHeader` exactly — not exported from the
 * OSS package's public barrel (target-builder internal), so pinned here as a
 * literal: a drift in that format is exactly what this test exists to catch. */
function header(sourcePath: string): string {
  return `<!-- generated by OuterLayer from ${sourcePath} — edit the source, not this file -->\n`;
}

function write(rootDir: string, relPath: string, content: string): void {
  const abs = join(rootDir, relPath);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content);
}

/** Target selection comes only from .outerlayer/config.json (no --target flag). */
function writeConfig(rootDir: string, targets: string[]): void {
  write(rootDir, ".outerlayer/config.json", JSON.stringify({ targets }));
}

const MCP_JSON =
  '{\n  "mcpServers": {\n    "api": {\n      "url": "https://api.example.com",\n      "type": "http"\n    }\n  }\n}\n';

function writeFixture(rootDir: string): void {
  write(rootDir, ".outerlayer/AGENTS.md", "Root instructions.\n");
  write(
    rootDir,
    ".outerlayer/skills/deploy-checklist/SKILL.md",
    "---\nname: deploy-checklist\ndescription: Steps to deploy safely.\n---\nRun the checklist.\n",
  );
  write(rootDir, ".outerlayer/skills/deploy-checklist/scripts/run.sh", "#!/bin/sh\necho deploy\n");
  write(
    rootDir,
    ".outerlayer/skills/onboarding/SKILL.md",
    "---\nname: onboarding\ndescription: Onboard a new engineer.\n---\nRead the docs.\n",
  );
  write(rootDir, ".outerlayer/skills/onboarding/references/setup.md", "Install dependencies.\n");
  write(rootDir, ".outerlayer/skills/onboarding/assets/logo.png", "PNGDATA");
  write(rootDir, ".outerlayer/commands/ship.md", "---\ndescription: Ship the current branch.\n---\nRun the ship script.\n");
  write(rootDir, ".outerlayer/mcp.json", MCP_JSON);
  write(rootDir, "apps/api/.outerlayer/AGENTS.md", "API scope instructions.\n");
}

/** Reads back files in the given order (callers pass `result.files`, which
 * `emitTree` already sorts by `localeCompare` — re-sorting here with a plain
 * `.sort()` would use UTF-16 code-unit order instead and could disagree). */
function readWritten(rootDir: string, paths: string[]): Array<{ path: string; content: string }> {
  return paths.map((path) => ({ path, content: readFileSync(join(rootDir, path), "utf8") }));
}

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "ol-emit-"));
  writeFixture(root);
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("runEmit — claude-code target", () => {
  it("compiles the fixture tree into Claude Code's native layout, byte-exact", () => {
    writeConfig(root, ["claude-code"]);
    const result = runEmit({ cwd: root, quiet: true });

    expect(result.exitCode).toBe(0);
    expect(result.errors).toEqual([]);
    expect(result.files).toEqual([
      ".claude/commands/ship.md",
      ".claude/skills/deploy-checklist/SKILL.md",
      ".claude/skills/onboarding/references/setup.md",
      ".claude/skills/onboarding/SKILL.md",
      ".mcp.json",
      "apps/api/CLAUDE.md",
      "CLAUDE.md",
    ]);
    expect(result.copies).toEqual([
      ".claude/skills/deploy-checklist/scripts/run.sh",
      ".claude/skills/onboarding/assets/logo.png",
    ]);

    expect(readWritten(root, result.files)).toEqual(
      [
        {
          path: ".claude/commands/ship.md",
          content: header(".outerlayer/commands/ship.md") + "---\ndescription: Ship the current branch.\n---\nRun the ship script.\n",
        },
        {
          path: ".claude/skills/deploy-checklist/SKILL.md",
          content:
            header(".outerlayer/skills/deploy-checklist/SKILL.md") +
            "---\nname: deploy-checklist\ndescription: Steps to deploy safely.\n---\nRun the checklist.\n",
        },
        {
          path: ".claude/skills/onboarding/references/setup.md",
          content: header(".outerlayer/skills/onboarding/references/setup.md") + "Install dependencies.\n",
        },
        {
          path: ".claude/skills/onboarding/SKILL.md",
          content:
            header(".outerlayer/skills/onboarding/SKILL.md") +
            "---\nname: onboarding\ndescription: Onboard a new engineer.\n---\nRead the docs.\n",
        },
        { path: ".mcp.json", content: MCP_JSON },
        { path: "apps/api/CLAUDE.md", content: header("apps/api/.outerlayer/AGENTS.md") + "API scope instructions.\n" },
        { path: "CLAUDE.md", content: header(".outerlayer/AGENTS.md") + "Root instructions.\n" },
      ].sort((a, b) => a.path.localeCompare(b.path)),
    );

    // Copies are byte-identical to their sources.
    expect(readFileSync(join(root, ".claude/skills/deploy-checklist/scripts/run.sh"), "utf8")).toBe(
      readFileSync(join(root, ".outerlayer/skills/deploy-checklist/scripts/run.sh"), "utf8"),
    );
    expect(readFileSync(join(root, ".claude/skills/onboarding/assets/logo.png"), "utf8")).toBe(
      readFileSync(join(root, ".outerlayer/skills/onboarding/assets/logo.png"), "utf8"),
    );
  });
});

describe("runEmit — cursor target", () => {
  it("compiles the fixture tree into Cursor's native layout, byte-exact", () => {
    writeConfig(root, ["cursor"]);
    const result = runEmit({ cwd: root, quiet: true });

    expect(result.exitCode).toBe(0);
    expect(result.errors).toEqual([]);
    expect(result.files).toEqual(
      [
        ".agents/skills/deploy-checklist/SKILL.md",
        ".agents/skills/onboarding/references/setup.md",
        ".agents/skills/onboarding/SKILL.md",
        ".cursor/commands/ship.md",
        ".cursor/mcp.json",
        "apps/api/AGENTS.md",
        "AGENTS.md",
      ].sort((a, b) => a.localeCompare(b)),
    );
    expect(result.copies).toEqual([
      ".agents/skills/deploy-checklist/scripts/run.sh",
      ".agents/skills/onboarding/assets/logo.png",
    ]);

    expect(readWritten(root, result.files)).toEqual(
      [
        {
          path: ".agents/skills/deploy-checklist/SKILL.md",
          content:
            header(".outerlayer/skills/deploy-checklist/SKILL.md") +
            "---\nname: deploy-checklist\ndescription: Steps to deploy safely.\n---\nRun the checklist.\n",
        },
        {
          path: ".agents/skills/onboarding/references/setup.md",
          content: header(".outerlayer/skills/onboarding/references/setup.md") + "Install dependencies.\n",
        },
        {
          path: ".agents/skills/onboarding/SKILL.md",
          content:
            header(".outerlayer/skills/onboarding/SKILL.md") +
            "---\nname: onboarding\ndescription: Onboard a new engineer.\n---\nRead the docs.\n",
        },
        {
          path: ".cursor/commands/ship.md",
          content: header(".outerlayer/commands/ship.md") + "<!-- Ship the current branch. -->\nRun the ship script.\n",
        },
        // Native `${VAR}` syntax has no rewrite target here — reserializes identically.
        { path: ".cursor/mcp.json", content: MCP_JSON },
        { path: "apps/api/AGENTS.md", content: header("apps/api/.outerlayer/AGENTS.md") + "API scope instructions.\n" },
        { path: "AGENTS.md", content: header(".outerlayer/AGENTS.md") + "Root instructions.\n" },
      ].sort((a, b) => a.path.localeCompare(b.path)),
    );
  });
});

describe("runEmit — codex target (AGENTS.md tier)", () => {
  it("emits AGENTS.md only, warning once per unsupported content kind present", () => {
    writeConfig(root, ["codex"]);
    const result = runEmit({ cwd: root, quiet: true });

    expect(result.exitCode).toBe(0);
    expect(result.errors).toEqual([]);
    expect(result.files).toEqual(["AGENTS.md", "apps/api/AGENTS.md"]);
    expect(result.copies).toEqual([]);
    expect(result.warnings).toEqual([
      { path: "codex:command", code: "unsupported_on_target", message: '"command" content is not emitted for codex (AGENTS.md-only tier in v1)' },
      { path: "codex:mcp", code: "unsupported_on_target", message: '"mcp" content is not emitted for codex (AGENTS.md-only tier in v1)' },
      { path: "codex:skill", code: "unsupported_on_target", message: '"skill" content is not emitted for codex (AGENTS.md-only tier in v1)' },
    ]);
    expect(readWritten(root, result.files)).toEqual([
      { path: "AGENTS.md", content: header(".outerlayer/AGENTS.md") + "Root instructions.\n" },
      { path: "apps/api/AGENTS.md", content: header("apps/api/.outerlayer/AGENTS.md") + "API scope instructions.\n" },
    ]);
  });
});

describe("runEmit — determinism", () => {
  it("two runs over the same tree, with the same config, produce byte-identical results", () => {
    writeConfig(root, ["claude-code", "cursor"]);
    const first = runEmit({ cwd: root, quiet: true });
    const second = runEmit({ cwd: root, quiet: true });

    expect(second.files).toEqual(first.files);
    expect(second.copies).toEqual(first.copies);
    expect(second.warnings).toEqual(first.warnings);
    expect(second.errors).toEqual(first.errors);
    expect(readWritten(root, second.files)).toEqual(readWritten(root, first.files));
  });
});

describe("runEmit — config refusal (no --target flag anywhere)", () => {
  it("throws EmitError, exit-worthy (1), and writes nothing when .outerlayer/config.json is absent", () => {
    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(EmitError);
    expect(existsSync(join(root, "CLAUDE.md"))).toBe(false);
    expect(existsSync(join(root, ".claude"))).toBe(false);
  });

  it("throws EmitError with the exact actionable message when config is absent", () => {
    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(EmitError);
    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(
      'no .outerlayer/config.json with a non-empty targets array — create one, e.g. {"targets": ["claude-code"]}',
    );
  });

  it("refuses with the SAME actionable message, exit 1, and writes nothing when targets is an empty array", () => {
    writeConfig(root, []);

    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(
      'no .outerlayer/config.json with a non-empty targets array — create one, e.g. {"targets": ["claude-code"]}',
    );
    expect(existsSync(join(root, "CLAUDE.md"))).toBe(false);
    expect(existsSync(join(root, ".claude"))).toBe(false);
  });

  it("surfaces the specific field error (not the generic refusal) for an unknown target id — the file DOES specify targets", () => {
    writeConfig(root, ["not-a-real-target"]);

    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(EmitError);
    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(/unknown target id "not-a-real-target"/);
    expect(existsSync(join(root, ".claude"))).toBe(false);
  });

  it("surfaces malformed JSON as an invalid-config error, not the generic missing-config refusal", () => {
    write(root, ".outerlayer/config.json", "{ targets: [");

    expect(() => runEmit({ cwd: root, quiet: true })).toThrow(/invalid \.outerlayer\/config\.json/);
    expect(existsSync(join(root, ".claude"))).toBe(false);
  });
});

describe("runEmit --json", () => {
  it("emits parsable JSON with the exact targets/files/copies/warnings/errors shape", () => {
    writeConfig(root, ["claude-code"]);
    const result = runEmit({ cwd: root, quiet: true, json: true });
    const parsed = JSON.parse(result.output) as {
      targets: string[];
      files: string[];
      copies: string[];
      warnings: unknown[];
      errors: unknown[];
    };
    expect(parsed).toEqual({
      targets: ["claude-code"],
      files: result.files,
      copies: result.copies,
      warnings: [],
      errors: [],
    });
  });
});

describe("runEmit --check", () => {
  it("a freshly emitted tree is clean — exit 0, empty drift", () => {
    writeConfig(root, ["claude-code"]);
    runEmit({ cwd: root, quiet: true });
    const result = runEmit({ cwd: root, check: true, quiet: true });
    expect(result.exitCode).toBe(0);
    expect(result.drift).toEqual([]);
    expect(result.files).toEqual([]);
    expect(result.copies).toEqual([]);
  });

  it("detects a missing output and writes nothing while reporting it", () => {
    writeConfig(root, ["claude-code"]);
    runEmit({ cwd: root, quiet: true });
    rmSync(join(root, "CLAUDE.md"));

    const result = runEmit({ cwd: root, check: true, quiet: true });

    expect(result.exitCode).toBe(1);
    expect(result.drift).toEqual([{ kind: "missing", path: "CLAUDE.md" }]);
    expect(existsSync(join(root, "CLAUDE.md"))).toBe(false); // --check never writes
  });

  it("detects content drift on an edited generated file and leaves it untouched", () => {
    writeConfig(root, ["claude-code"]);
    runEmit({ cwd: root, quiet: true });
    writeFileSync(join(root, ".claude/commands/ship.md"), "someone hand-edited this\n");

    const result = runEmit({ cwd: root, check: true, quiet: true });

    expect(result.exitCode).toBe(1);
    expect(result.drift).toEqual([{ kind: "content", path: ".claude/commands/ship.md" }]);
    // --check reports drift, it does not fix it.
    expect(readFileSync(join(root, ".claude/commands/ship.md"), "utf8")).toBe("someone hand-edited this\n");
  });

  it("a headerless user file sitting at a would-be output path is content drift, never silently overwritten", () => {
    writeConfig(root, ["claude-code"]);
    // No prior `emit` run — CLAUDE.md here is a genuine user file, not ours.
    write(root, "CLAUDE.md", "These are my own hand-written notes, not generated.\n");

    const result = runEmit({ cwd: root, check: true, quiet: true });

    expect(result.exitCode).toBe(1);
    expect(result.drift).toContainEqual({ kind: "content", path: "CLAUDE.md" });
    expect(readFileSync(join(root, "CLAUDE.md"), "utf8")).toBe(
      "These are my own hand-written notes, not generated.\n",
    );
  });

  it("flags a generated file as orphaned once its source is gone, and leaves it on disk", () => {
    writeConfig(root, ["claude-code"]);
    runEmit({ cwd: root, quiet: true });
    rmSync(join(root, ".outerlayer/AGENTS.md")); // the source CLAUDE.md was generated from

    const result = runEmit({ cwd: root, check: true, quiet: true });

    expect(result.exitCode).toBe(1);
    expect(result.drift).toContainEqual({ kind: "orphaned", path: "CLAUDE.md" });
    expect(existsSync(join(root, "CLAUDE.md"))).toBe(true); // reported, never deleted
  });

  it("does not flag a target's own output as orphaned just because a narrower config was checked", () => {
    // cursor's AGENTS.md derives from the same still-present source as claude-code's CLAUDE.md.
    writeConfig(root, ["claude-code", "cursor"]);
    runEmit({ cwd: root, quiet: true });
    writeConfig(root, ["claude-code"]);
    const result = runEmit({ cwd: root, check: true, quiet: true });
    expect(result.drift?.some((d) => d.path === "AGENTS.md")).toBe(false);
  });

  it("missing config still refuses under --check, exit 1, nothing written", () => {
    expect(() => runEmit({ cwd: root, check: true, quiet: true })).toThrow(EmitError);
    expect(existsSync(join(root, "CLAUDE.md"))).toBe(false);
  });

  it("--json shape for --check", () => {
    writeConfig(root, ["claude-code"]);
    runEmit({ cwd: root, quiet: true });
    const result = runEmit({ cwd: root, check: true, json: true, quiet: true });
    const parsed = JSON.parse(result.output) as { targets: string[]; drift: unknown[]; warnings: unknown[]; errors: unknown[] };
    expect(parsed).toEqual({ targets: ["claude-code"], drift: [], warnings: [], errors: [] });
  });
});
