import { describe, expect, it } from "vitest";
import { parseUserTurn } from "../user-turn";

describe("parseUserTurn", () => {
  it("lifts a slash command out of the tag soup and keeps no markup in the body", () => {
    const raw = [
      "<command-name>/clear</command-name>",
      "        <command-message>clear</command-message>",
      "        <command-args></command-args>",
    ].join("\n");
    expect(parseUserTurn(raw)).toEqual({
      command: "/clear",
      commandArgs: "",
      stdout: "",
      text: "",
      empty: false,
    });
  });

  it("keeps command arguments and stdout separate from each other", () => {
    const raw =
      "<command-name>/model</command-name><command-args>opus</command-args>" +
      "<local-command-stdout>Set model to opus</local-command-stdout>";
    expect(parseUserTurn(raw)).toEqual({
      command: "/model",
      commandArgs: "opus",
      stdout: "Set model to opus",
      text: "",
      empty: false,
    });
  });

  it("drops a turn that is only the local-command caveat, tagged or bare", () => {
    const tagged =
      "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>";
    const bare =
      "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.";
    expect(parseUserTurn(tagged).empty).toBe(true);
    expect(parseUserTurn(bare).empty).toBe(true);
    expect(parseUserTurn(tagged).text).toBe("");
    expect(parseUserTurn(bare).text).toBe("");
  });

  it("preserves the developer's own words when they ride alongside a command", () => {
    const raw = "<command-name>/model</command-name>\nuse opus for the rest of this session";
    const view = parseUserTurn(raw);
    expect(view.command).toBe("/model");
    expect(view.text).toBe("use opus for the rest of this session");
    expect(view.empty).toBe(false);
  });

  it("leaves an ordinary message untouched, angle brackets and all", () => {
    const raw = "compare Array<string> with Array<number> here";
    expect(parseUserTurn(raw)).toEqual({
      command: "",
      commandArgs: "",
      stdout: "",
      text: "compare Array<string> with Array<number> here",
      empty: false,
    });
  });

  it("treats an absent or empty turn as empty rather than throwing", () => {
    expect(parseUserTurn(null).empty).toBe(true);
    expect(parseUserTurn(undefined).empty).toBe(true);
    expect(parseUserTurn("   ").empty).toBe(true);
  });

  it("handles multiple commands in one turn without merging their text", () => {
    const raw =
      "<command-name>/clear</command-name><local-command-stdout>gone</local-command-stdout>" +
      "\nthen do the thing";
    const view = parseUserTurn(raw);
    expect(view.command).toBe("/clear");
    expect(view.stdout).toBe("gone");
    expect(view.text).toBe("then do the thing");
  });
});
